FROM golang:1.21 as builder

WORKDIR /app
ADD . .

RUN go build -ldflags="-s -w" -o ./dist/pst-agent main.go

FROM scratch as runtime

WORKDIR /app

COPY --from=builder /app/dist/pst-agent /app/pst-agent


EXPOSE 8081
ENTRYPOINT [ "pst-agent" ]