FROM golang:1.21 as builder

ARG proxy

WORKDIR /app
ADD . .

RUN if [ ! -z "$proxy" ]; then \
    export GOPROXY=https://goproxy.io,direct && \
    go build -ldflags="-s -w" -o ./dist/pst-agent cmd/pst-agent/main.go; \
    else \
    go build -ldflags="-s -w" -o ./dist/pst-agent cmd/pst-agent/main.go; \
    fi

FROM scratch as runtime

WORKDIR /app

COPY --from=builder /app/dist/pst-agent /app/pst-agent


EXPOSE 8081
ENTRYPOINT [ "pst-agent" ]